Noarch version
conda-forge/anndata-feedstock pull request #21
Opened 2022-03-02 14:55 UTC by HeavyTony2

Added the missing dependancy xlrd <2.0 and set it as noarch.

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2022-03-02 14:55 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found some lint.

Here's what I've got...


For **recipe**:

 * `noarch` packages can't have selectors. If the selectors are necessary, please remove `noarch: python`.

2022-03-02 14:58 UTC, HeavyTony2 commented
@conda-forge-admin, please rerender

2022-03-23 14:36 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I was trying to look for recipes to lint for you, but it appears we have a merge conflict.
Please try to merge or rebase with the base branch to resolve this conflict.

Please ping the 'conda-forge/core' team (using the @ notation in a comment) if you believe this is a bug.

2022-03-23 14:37 UTC, HeavyTony2 commented
@conda-forge-admin, please rerender

2022-03-24 12:40 UTC, flying-sheep requested changes
Everything except for conditional dependencies looks good.

2022-03-24 12:40 UTC, flying-sheep commented on recipe/meta.yaml
> +    - typing_extensions
Both of those are only necessary in Python <3.8.

Can you make it so they don’t get installed in Python 3.8+?

2022-03-24 15:58 UTC, ivirshup commented
We also no longer rely on xlrd, so it probably shouldn't be added to the dependency list.

I was wondering, does `noarch` imply we can't have python version restrictions?

2022-05-17 18:16 UTC, HeavyTony2 commented
> We also no longer rely on xlrd, so it probably shouldn't be added to the dependency list.
> 
> I was wondering, does `noarch` imply we can't have python version restrictions?

Sorry for the late answer. The answer is no. In fact, with a noarch version you have to set a python version restriction. The typical one is `python >=3.6` but it could be `python <=4` too for example.

2022-05-17 18:18 UTC, HeavyTony2 commented
@conda-forge-admin, please rerender

2022-05-17 18:27 UTC, closed without merging